openapi: 3.0.3
info:
  title: Test Announcement API
  description: Test Announcement API
  version: 1.0.0
servers:
  - url: https://dev.api.test.com/oms/v2
    description: dev server
  - url: http://local.api.test.com/oms/v2
    description: local server

paths:
  /:
    get:
      tags:
        - inbound_order
      summary: batch_query_inbound_order inbound_order
      operationId: inbound_order#batch_query_inbound_order
      parameters:
        - name: order_numbers
          in: query
          description: order number
          allowEmptyValue: true
          schema:
            type: array
            items:
              type: string
              example: Ipsa vitae qui ut.
            description: order number
            example:
              - xxx1234
            maxItems: 50
          example:
            - xxx1234
        - name: status
          in: query
          description: status
          allowEmptyValue: true
          schema:
            type: integer
            description: status
            example: 1
            minimum: 0
            maximum: 100
          example: 1
        - name: current
          in: query
          description: current
          allowEmptyValue: true
          schema:
            type: integer
            description: current
            example: 1
            minimum: 1
          example: 1
        - name: page_size
          in: query
          description: page_size
          allowEmptyValue: true
          schema:
            type: integer
            description: page_size
            example: 1
            minimum: 1
            maximum: 50
          example: 1
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchQueryOrderRsp'
              example:
                code: 0
                data:
                  list:
                    - created_at: Voluptatem dolorum nihil quibusdam consequatur et
                        et.
                      description: Enim sit.
                      estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
                      id: 1335748255
                      items:
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                      order_number: Et necessitatibus quia culpa accusantium vel veritatis.
                      ship_at: Vero est.
                      status: 723093085
                      tracking_number: Beatae illum modi.
                      warehouse_name: Consequatur itaque aut nam optio magnam.
                    - created_at: Voluptatem dolorum nihil quibusdam consequatur et
                        et.
                      description: Enim sit.
                      estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
                      id: 1335748255
                      items:
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                      order_number: Et necessitatibus quia culpa accusantium vel veritatis.
                      ship_at: Vero est.
                      status: 723093085
                      tracking_number: Beatae illum modi.
                      warehouse_name: Consequatur itaque aut nam optio magnam.
                    - created_at: Voluptatem dolorum nihil quibusdam consequatur et
                        et.
                      description: Enim sit.
                      estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
                      id: 1335748255
                      items:
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                      order_number: Et necessitatibus quia culpa accusantium vel veritatis.
                      ship_at: Vero est.
                      status: 723093085
                      tracking_number: Beatae illum modi.
                      warehouse_name: Consequatur itaque aut nam optio magnam.
                    - created_at: Voluptatem dolorum nihil quibusdam consequatur et
                        et.
                      description: Enim sit.
                      estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
                      id: 1335748255
                      items:
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                        - product_barcode: Adipisci optio asperiores.
                          product_name: Aut doloremque aut saepe.
                          product_qty: 2042656415
                          product_sku: Enim quaerat at ut inventore.
                      order_number: Et necessitatibus quia culpa accusantium vel veritatis.
                      ship_at: Vero est.
                      status: 723093085
                      tracking_number: Beatae illum modi.
                      warehouse_name: Consequatur itaque aut nam optio magnam.
                  meta:
                    current: 1
                    page_size: 1
                    total: 1
                message: description error information
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
        - jwt_header_Authorization:
            - api:read
            - api:write
    post:
      tags:
        - inbound_order
      summary: create_inbound_order inbound_order
      operationId: inbound_order#create_inbound_order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInboundOrderRequestBody'
            example:
              description: xxxx
              estimated_arrival_at: "2022-04-14 00:00:00"
              items:
                - product_id: 159866018
                  product_qty: 1245746977
              ship_at: "2022-04-14 00:00:00"
              tracking_number: xxx
              warehouse_id: 1
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateInboundRsp'
              example:
                code: 0
                data:
                  order_number: Id sequi consequatur non voluptatibus nesciunt architecto.
                message: description error information
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
        - jwt_header_Authorization:
            - api:read
            - api:write
  /{order_number}:
    get:
      tags:
        - inbound_order
      summary: query_inbound_order inbound_order
      operationId: inbound_order#query_inbound_order
      parameters:
        - name: order_number
          in: path
          description: inbound order number (入库单序列号)
          required: true
          schema:
            type: string
            description: inbound order number (入库单序列号)
            example: xxx
          example: xxx
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryInboundOrderRequestBody'
            example:
              current: 1
              page_size: 1
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryInboundRsp'
              example:
                code: 0
                data:
                  created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
                  description: Enim sit.
                  estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
                  id: 1335748255
                  items:
                    - product_barcode: Adipisci optio asperiores.
                      product_name: Aut doloremque aut saepe.
                      product_qty: 2042656415
                      product_sku: Enim quaerat at ut inventore.
                    - product_barcode: Adipisci optio asperiores.
                      product_name: Aut doloremque aut saepe.
                      product_qty: 2042656415
                      product_sku: Enim quaerat at ut inventore.
                    - product_barcode: Adipisci optio asperiores.
                      product_name: Aut doloremque aut saepe.
                      product_qty: 2042656415
                      product_sku: Enim quaerat at ut inventore.
                    - product_barcode: Adipisci optio asperiores.
                      product_name: Aut doloremque aut saepe.
                      product_qty: 2042656415
                      product_sku: Enim quaerat at ut inventore.
                  order_number: Et necessitatibus quia culpa accusantium vel veritatis.
                  ship_at: Vero est.
                  status: 723093085
                  tracking_number: Beatae illum modi.
                  warehouse_name: Consequatur itaque aut nam optio magnam.
                message: description error information
        "401":
          description: Unauthorized response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
      security:
        - jwt_header_Authorization:
            - api:read
            - api:write
components:
  schemas:
    BatchQueryOrderInfo:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/QueryInboundData'
          description: list data
          example:
            - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
              description: Enim sit.
              estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
              id: 1335748255
              items:
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
              order_number: Et necessitatibus quia culpa accusantium vel veritatis.
              ship_at: Vero est.
              status: 723093085
              tracking_number: Beatae illum modi.
              warehouse_name: Consequatur itaque aut nam optio magnam.
            - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
              description: Enim sit.
              estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
              id: 1335748255
              items:
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
              order_number: Et necessitatibus quia culpa accusantium vel veritatis.
              ship_at: Vero est.
              status: 723093085
              tracking_number: Beatae illum modi.
              warehouse_name: Consequatur itaque aut nam optio magnam.
            - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
              description: Enim sit.
              estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
              id: 1335748255
              items:
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
              order_number: Et necessitatibus quia culpa accusantium vel veritatis.
              ship_at: Vero est.
              status: 723093085
              tracking_number: Beatae illum modi.
              warehouse_name: Consequatur itaque aut nam optio magnam.
        meta:
          $ref: '#/components/schemas/MetaData'
      example:
        list:
          - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
            description: Enim sit.
            estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
            id: 1335748255
            items:
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
            order_number: Et necessitatibus quia culpa accusantium vel veritatis.
            ship_at: Vero est.
            status: 723093085
            tracking_number: Beatae illum modi.
            warehouse_name: Consequatur itaque aut nam optio magnam.
          - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
            description: Enim sit.
            estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
            id: 1335748255
            items:
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
              - product_barcode: Adipisci optio asperiores.
                product_name: Aut doloremque aut saepe.
                product_qty: 2042656415
                product_sku: Enim quaerat at ut inventore.
            order_number: Et necessitatibus quia culpa accusantium vel veritatis.
            ship_at: Vero est.
            status: 723093085
            tracking_number: Beatae illum modi.
            warehouse_name: Consequatur itaque aut nam optio magnam.
        meta:
          current: 1
          page_size: 1
          total: 1
      required:
        - list
        - meta
    BatchQueryOrderRsp:
      type: object
      properties:
        code:
          type: integer
          description: code
          example: 0
          format: int64
        data:
          $ref: '#/components/schemas/BatchQueryOrderInfo'
        message:
          type: string
          description: message
          example: description error information
      example:
        code: 0
        data:
          list:
            - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
              description: Enim sit.
              estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
              id: 1335748255
              items:
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
              order_number: Et necessitatibus quia culpa accusantium vel veritatis.
              ship_at: Vero est.
              status: 723093085
              tracking_number: Beatae illum modi.
              warehouse_name: Consequatur itaque aut nam optio magnam.
            - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
              description: Enim sit.
              estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
              id: 1335748255
              items:
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
              order_number: Et necessitatibus quia culpa accusantium vel veritatis.
              ship_at: Vero est.
              status: 723093085
              tracking_number: Beatae illum modi.
              warehouse_name: Consequatur itaque aut nam optio magnam.
            - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
              description: Enim sit.
              estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
              id: 1335748255
              items:
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
              order_number: Et necessitatibus quia culpa accusantium vel veritatis.
              ship_at: Vero est.
              status: 723093085
              tracking_number: Beatae illum modi.
              warehouse_name: Consequatur itaque aut nam optio magnam.
            - created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
              description: Enim sit.
              estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
              id: 1335748255
              items:
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
                - product_barcode: Adipisci optio asperiores.
                  product_name: Aut doloremque aut saepe.
                  product_qty: 2042656415
                  product_sku: Enim quaerat at ut inventore.
              order_number: Et necessitatibus quia culpa accusantium vel veritatis.
              ship_at: Vero est.
              status: 723093085
              tracking_number: Beatae illum modi.
              warehouse_name: Consequatur itaque aut nam optio magnam.
          meta:
            current: 1
            page_size: 1
            total: 1
        message: description error information
      required:
        - code
        - message
    CreateInboundData:
      type: object
      properties:
        order_number:
          type: string
          description: inbound order number (入库单序列号)
          example: Omnis ab ratione non non et.
      example:
        order_number: Praesentium placeat.
      required:
        - order_number
    CreateInboundItem:
      type: object
      properties:
        product_id:
          type: integer
          description: product id (产品ID)
          example: 981810401
          format: int32
        product_qty:
          type: integer
          description: product qty (产品数量)
          example: 1141174112
          format: int32
      example:
        product_id: 276783672
        product_qty: 1034633411
      required:
        - product_id
        - product_qty
    CreateInboundOrderRequestBody:
      type: object
      properties:
        description:
          type: string
          description: description (描述）
          example: xxxx
        estimated_arrival_at:
          type: string
          description: estimated arrival time (预估到达时间)
          example: "2022-04-14 00:00:00"
        items:
          type: array
          items:
            $ref: '#/components/schemas/CreateInboundItem'
          description: items
          example:
            - product_id: 159866018
              product_qty: 1245746977
          minItems: 1
        ship_at:
          type: string
          description: ship time (发货时间)
          example: "2022-04-14 00:00:00"
        tracking_number:
          type: string
          description: tracking number (运单号)
          example: xxx
        warehouse_id:
          type: integer
          description: warehouse id (仓库ID)
          example: 1
          format: int32
      example:
        description: xxxx
        estimated_arrival_at: "2022-04-14 00:00:00"
        items:
          - product_id: 159866018
            product_qty: 1245746977
        ship_at: "2022-04-14 00:00:00"
        tracking_number: xxx
        warehouse_id: 1
      required:
        - items
        - warehouse_id
    CreateInboundRsp:
      type: object
      properties:
        code:
          type: integer
          description: code
          example: 0
          format: int64
        data:
          $ref: '#/components/schemas/CreateInboundData'
        message:
          type: string
          description: message
          example: description error information
      example:
        code: 0
        data:
          order_number: Id sequi consequatur non voluptatibus nesciunt architecto.
        message: description error information
      required:
        - code
        - message
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
        - name
        - id
        - message
        - temporary
        - timeout
        - fault
    MetaData:
      type: object
      properties:
        current:
          type: integer
          description: current
          example: 1
          minimum: 1
        page_size:
          type: integer
          description: page_size
          example: 1
          minimum: 1
        total:
          type: integer
          description: total
          example: 1
          format: int64
      description: MetaData describes the MetaData
      example:
        current: 1
        page_size: 1
        total: 1
      required:
        - current
        - page_size
        - total
    QueryInboundData:
      type: object
      properties:
        created_at:
          type: string
          description: created time (创建时间)
          example: Maiores incidunt error dolorem vel.
        description:
          type: string
          description: description (描述)
          example: Reprehenderit voluptatem quis quas est dolorem.
        estimated_arrival_at:
          type: string
          description: estimated arrival time (预估到达时间)
          example: Ut sed dicta fugit repellat molestias sapiente.
        id:
          type: integer
          description: inbound order id (入库单ID)
          example: 32792472
          format: int32
        items:
          type: array
          items:
            $ref: '#/components/schemas/QueryInboundItem'
          description: inbound order items (入库单items)
          example:
            - product_barcode: Adipisci optio asperiores.
              product_name: Aut doloremque aut saepe.
              product_qty: 2042656415
              product_sku: Enim quaerat at ut inventore.
            - product_barcode: Adipisci optio asperiores.
              product_name: Aut doloremque aut saepe.
              product_qty: 2042656415
              product_sku: Enim quaerat at ut inventore.
        order_number:
          type: string
          description: inbound order number (入库单序列号)
          example: Et eveniet tempore cum.
        ship_at:
          type: string
          description: ship time (发货时间)
          example: At qui placeat quibusdam id eveniet.
        status:
          type: integer
          description: inbound order status (入库单状态)
          example: 481314035
          format: int32
        tracking_number:
          type: string
          description: tracking number (运单号)
          example: Omnis blanditiis voluptates neque.
        warehouse_name:
          type: string
          description: warehouse name (仓库名称)
          example: Dicta fuga est totam qui blanditiis voluptatem.
      example:
        created_at: Blanditiis nesciunt recusandae qui sunt.
        description: Sit sit doloribus dolor.
        estimated_arrival_at: Quia sunt facilis quam.
        id: 722674706
        items:
          - product_barcode: Adipisci optio asperiores.
            product_name: Aut doloremque aut saepe.
            product_qty: 2042656415
            product_sku: Enim quaerat at ut inventore.
          - product_barcode: Adipisci optio asperiores.
            product_name: Aut doloremque aut saepe.
            product_qty: 2042656415
            product_sku: Enim quaerat at ut inventore.
          - product_barcode: Adipisci optio asperiores.
            product_name: Aut doloremque aut saepe.
            product_qty: 2042656415
            product_sku: Enim quaerat at ut inventore.
        order_number: Assumenda libero et impedit.
        ship_at: Perferendis laboriosam.
        status: 162085136
        tracking_number: Incidunt veritatis repellat dolores non.
        warehouse_name: Quisquam aliquid quidem labore sed.
      required:
        - id
        - order_number
        - warehouse_name
        - tracking_number
        - ship_at
        - estimated_arrival_at
        - description
        - created_at
        - status
        - items
    QueryInboundItem:
      type: object
      properties:
        product_barcode:
          type: string
          description: product barcode (产品Barcode)
          example: Fuga temporibus mollitia.
        product_name:
          type: string
          description: product id (产品ID)
          example: Dignissimos unde quibusdam.
        product_qty:
          type: integer
          description: product qty (产品数量)
          example: 1775195954
          format: int32
        product_sku:
          type: string
          description: product sku (产品SKu)
          example: Quia ad dolor nihil ipsum consequatur et.
      example:
        product_barcode: Explicabo quisquam ea dolorem nemo.
        product_name: Asperiores consequuntur dolor qui illo iusto illo.
        product_qty: 506754054
        product_sku: Minus est eveniet dolorem.
      required:
        - product_name
        - product_qty
        - product_sku
        - product_barcode
    QueryInboundOrderRequestBody:
      type: object
      properties:
        current:
          type: integer
          description: current
          example: 1
          minimum: 1
        page_size:
          type: integer
          description: page_size
          example: 1
          minimum: 1
          maximum: 50
      example:
        current: 1
        page_size: 1
    QueryInboundRsp:
      type: object
      properties:
        code:
          type: integer
          description: code
          example: 0
          format: int64
        data:
          $ref: '#/components/schemas/QueryInboundData'
        message:
          type: string
          description: message
          example: description error information
      example:
        code: 0
        data:
          created_at: Voluptatem dolorum nihil quibusdam consequatur et et.
          description: Enim sit.
          estimated_arrival_at: Quia nihil debitis enim exercitationem repudiandae.
          id: 1335748255
          items:
            - product_barcode: Adipisci optio asperiores.
              product_name: Aut doloremque aut saepe.
              product_qty: 2042656415
              product_sku: Enim quaerat at ut inventore.
            - product_barcode: Adipisci optio asperiores.
              product_name: Aut doloremque aut saepe.
              product_qty: 2042656415
              product_sku: Enim quaerat at ut inventore.
            - product_barcode: Adipisci optio asperiores.
              product_name: Aut doloremque aut saepe.
              product_qty: 2042656415
              product_sku: Enim quaerat at ut inventore.
            - product_barcode: Adipisci optio asperiores.
              product_name: Aut doloremque aut saepe.
              product_qty: 2042656415
              product_sku: Enim quaerat at ut inventore.
          order_number: Et necessitatibus quia culpa accusantium vel veritatis.
          ship_at: Vero est.
          status: 723093085
          tracking_number: Beatae illum modi.
          warehouse_name: Consequatur itaque aut nam optio magnam.
        message: description error information
      required:
        - code
        - message
  securitySchemes:
    jwt_header_Authorization:
      type: http
      description: Secures endpoint by requiring a valid JWT token retrieved via the
        signin endpoint
      scheme: bearer
tags:
  - name: inbound_order
    description: The order service performs operations on inbound service
